### ISSUE TITLE
Breaking build in `0.24.7`: `Operation` in module `super::super::super::super::longrunning`

### ISSUE THREAD

**Issue by zerosnacks** [abdolence/gcloud-sdk-rs#144]
Since updating to `0.24.7` I'm running into a build issue using `gcloud-sdk-rs` using the `google-cloud-kms-v1` feature flag:

```
gcloud-sdk = { version = "0.24.7", features = ["google-cloud-kms-v1"] }
```

```
error[E0412]: cannot find type `Operation` in module `super::super::super::super::longrunning`
    --> /home/zerosnacks/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gcloud-sdk-0.24.7/src/../genproto/google.cloud.kms.v1.rs:1432:70
     |
1432 |             tonic::Response<super::super::super::super::longrunning::Operation>,
     |                                                                      ^^^^^^^^^ not found in `super::super::super::super::longrunning`

For more information about this error, try `rustc --explain E0412`.
```

Verified that downgrading to `0.24.6` resolves the issue.

**Comment by abdolence** [comment]
Thanks for reporting it, 0.24.7 only contained refreshed specs, probably something changed there. I'll verify the changes and come back to you.

**Comment by abdolence** [comment]
@zerosnacks Seems Google has added the dependency between KMS spec and long running spec.
This happened before for other specs as well.

Fortunately the fix is easy:
`features = ["google-cloud-kms-v1", "google-longrunning"]`
you need to add that "google-longrunning" feature.

Let me know if it doesn't help you

**Comment by zerosnacks** [comment]
That fixes the issue, thanks for the quick response and help @abdolence!

**Comment by abdolence** [comment]
Glad to hear it helped.

Sorry it was disruptive for you, but I have little control over dependencies between Google features, this happens from time to time.
